#!/bin/bash
#=======================================================================
#
#   Kython 1.0
#
#   Usage:         kython [FLAGS] INFILE
#
#   Description:   Runs the input script through the kython
#                  interpreter and then the system python3 interpreter.
#   FLAGS:
#      -2py        Stores interpretted python
#                  as INFILE.py
#
#=======================================================================

argL=($@) # makes arg string into list
in=$1
out=$(dirname $in)/.$(basename $in).py # output hidden by default
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

n=$(expr $# - 1) # last arg index
if [[ $n -ge 0 ]]; then           ##
  argF="${argL[$n]}"               #
  if [[ $argF == -2py ]]; then     # remove -2py from args
    argL=( ${argL[@]:0:n} )        #
fi; fi                            ##

argL=(${argL[@]:1}) # remove script name from argL
args=${argL[@]}

 # run kython interpreter on input
$SCRIPTPATH/kython_internal_modules/kythonInterpreter $in $out
if [[ $? == 0 ]]; then          # if no error from kython
   python3 $out $args           # run output with python3
   if [[ $argF == -2py ]]; then    ##
      mv $out $in.py                # if last arg is -2py,
   else                             # save python script
      rm $out                       #
   fi                              ##
else
   echo "Kython syntax errors.  Exiting"
fi
