#!/bin/bash

# Determine profile used
if [[ -f ~/.bashrc ]]; then
  profile=".bashrc"
elif [[ -f ~/.bash_profile ]]; then
  profile=".bash_profile"
elif [[ -f ~/.profile ]]; then
  profile=".profile"
fi

if [[ $1 != "" ]]; then # Directory given as arg
  bin=$1
  cmd='rm -r'
else # Directory not given, assume /bin
  bin='/bin'
  cmd='sudo rm -r'
  sudo -v
fi

echo -e "\n* Removing kython from $bin"
$cmd $bin/kython
$cmd $bin/kython_internal_modules
echo "* Done"

echo -e "\n* Uninstalling vim syntax"
rm ~/.vim/LICENSE_KYTHON
rm ~/.vim/syntax/vim-syntax-kython.vim
rm ~/.vim/ftdetect/vim-syntax-kython.vim
echo "* Done"

echo -e "\n* Uninstalling atom language"
rm -r ~/.atom/packages/language-kython
echo "* Done"

if [[ $(grep ADDED_BY_KYTHON ~/$profile) != "" ]]; then
  echo "* Removing path export lines from ~/$profile"
  sed -i '/^.*ADDED_BY_KYTHON\s*$/d' ~/$profile
  echo "* Done"
fi

echo -e "\n\t\t~ Kython Uninstall Complete ~\n"
